-- SQL Import for Gym Leads
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('The Beast house', 'The Beast house', 'charibatia rd', '7978633375', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the sweat and fit gym arena', 'the sweat and fit gym arena', 'jail rd', '7978275190', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness club gym choudwar', 'fitness club gym choudwar', 'kalinga chak', '7008463064', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('maxburn gym', 'maxburn gym', 'infront choudwar college', '9438683146', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('squard fitness', 'squard fitness', 'infront of honda showroom', NULL, 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('mahaveer gym industries', 'mahaveer gym industries', 'bhabadeipur', '8282826384', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('maxburn gym ibroad', 'maxburn gym ibroad', 'ib road', '9438683146', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('popular gym2.0-best unisex gym', 'popular gym2.0-best unisex gym', 'mangalabag,nuapatna', '9338856611', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('core fitness', 'core fitness', 'buxi bazar', '9114892019', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('max burn gym', 'max burn gym', 'machhua bazar,cuttack', '9438683146', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('momentum fitness', 'momentum fitness', 'macchua bazar', '7077109999', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('maxburn gym jagatpur', 'maxburn gym jagatpur', 'jagatpur', '9438683146', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('club1percent gym', 'club1percent gym', 'alisha bazar', '7064597752', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('uptown fitness 2', 'uptown fitness 2', 'ipicol square,jagatpur', NULL, 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('12*7finess', '12*7finess', 'mangalabag', '9937090482', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('tiger  fitness unisex gym', 'tiger  fitness unisex gym', 'gurujhatia', '8249735229', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('refrom fitness - ladies gym', 'refrom fitness - ladies gym', 'shelter chak,cuttack', '7978078522', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ananda fitness', 'ananda fitness', 'buxi bazar', '9827833808', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('DNA gym(BHANPUR)', 'DNA gym(BHANPUR)', 'Cuttack sadar', '7008807554', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('equinox gym the complete body', 'equinox gym the complete body', 'jobra colony', '9040158669', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness mantra gym', 'fitness mantra gym', 'nandi sahi', '9338881999', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the gym factory', 'the gym factory', 'surya vihar', '9853667711', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('HPN fitness', 'HPN fitness', 'managalabag', '9778023443', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('titan gym', 'titan gym', 'naya bazar', '6372256060', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('evolve fitness cuttack', 'evolve fitness cuttack', 'Lic colony', '7377711179', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('momentum fitness', 'momentum fitness', 'macchua bazar', '7077109999', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('armani fitness studio', 'armani fitness studio', 'dargha bazar', '7008168853', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('iron fist', 'iron fist', 'cda9', '8249405541', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('max burn gym', 'max burn gym', 'buxi bazar', '9438683146', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('stark gym', 'stark gym', 'dolamundai', '7381311775', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('bootcamp fitness', 'bootcamp fitness', 'dargha bazar', '9439956521', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('communefitness', 'communefitness', 'college square', '9938581222', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('uptown fitness', 'uptown fitness', 'badambadi', '8847830773', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fityness mantra', 'fityness mantra', 'mahanadi vihar', '8249068372', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('mo gym and cafe', 'mo gym and cafe', 'omp', '7205310024', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('dc multigym & fitness', 'dc multigym & fitness', 'rajendra nagar', NULL, 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('gym wavveq', 'gym wavveq', 'mahanadi vihar', '7008757062', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('DNA gym(BHANPUR)', 'DNA gym(BHANPUR)', 'patana', '7008807554', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness mantra gym', 'fitness mantra gym', 'cda9', '7008851554', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('sonaaerobics nad fitness', 'sonaaerobics nad fitness', 'mahanadi vihar', NULL, 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('reform fitness', 'reform fitness', 'shelter chak,cuttack', '7978078522', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('oxygen + gym', 'oxygen + gym', 'nupada,cuttack', '8637232132', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Thunder', 'Thunder', 'gandar', '9658313597', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('v tone fitness unisex gym', 'v tone fitness unisex gym', 'cda10', '7008775206', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the fitness studio', 'the fitness studio', 'buxi bazar', '9439828776', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('transform fitness club', 'transform fitness club', 'cda6', '8093008013', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('hercules fitness', 'hercules fitness', 'cda11', '9937138288', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('The Beast house', 'The Beast house', 'charibatia rd', '7978633375', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('dream fit gym', 'dream fit gym', 'balikuda', '9348787002', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('body shaper', 'body shaper', 'badambadi', '9238308086', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('live fit unisex gym', 'live fit unisex gym', 'link road', '9853364653', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('body by biren 24*7 gym', 'body by biren 24*7 gym', 'cda10', '9078825115', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('being fit gym', 'being fit gym', 'tangi', '7438800809', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('strong house gym', 'strong house gym', 'cda10', '9438683146', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('new age living gym cenmter', 'new age living gym cenmter', 'municpal colony', '9861013120', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('force gym unisex', 'force gym unisex', 'bidanasi', '7377711109', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ma fitness gym', 'ma fitness gym', 'rajabagicha', '9583123939', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('sp fitness empire', 'sp fitness empire', 'cda10', '7855885256', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('phonix gym', 'phonix gym', 'bidanasi', '9853160626', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('elevate fitness hub', 'elevate fitness hub', 'brahmnapur', '7205065339', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('chandi pro fitness', 'chandi pro fitness', 'badambadi', '8917363518', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('bodypower store odisha', 'bodypower store odisha', 'ranihat', '9853877118', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('vtone fitness2.0', 'vtone fitness2.0', 'trisulia', '7008775206', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('sunil fitness', 'sunil fitness', 'khandar', '9337001030', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('power house gym', 'power house gym', 'link road', '9437064679', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness ada', 'fitness ada', 'tanarnapasana', '9692133647', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('sim line ft', 'sim line ft', 'chauliaganj', '9861062204', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fittness fury', 'fittness fury', 'cda10', '7894789444', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('oca gym', 'oca gym', 'stadium rd', '9658910637', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('online fit club', 'online fit club', 'dolamundai', '9439063754', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('syndicate gym industries', 'syndicate gym industries', 'siba bazar', '9316970498', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('tiger  fitness unisex gym', 'tiger  fitness unisex gym', 'gurujhatia', '8249735229', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('train2 infity', 'train2 infity', 'salipur', '8596999000', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit food hub', 'fit food hub', 'gandarpur', '7008280184', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('treadmill service', 'treadmill service', 'khan nagar', '9938777314', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('highborn nutrion cuttack', 'highborn nutrion cuttack', 'naya sadak', '8280002552', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('arya fitness', 'arya fitness', 'jankana', '7978100322', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ffit or fight unisex massage center', 'ffit or fight unisex massage center', 'mahanadi vihar', '9337359310', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the popeye theory', 'the popeye theory', 'college square', '9123088654', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness galaxy', 'fitness galaxy', 'adaspur', '7008669134', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('beingayogic academy', 'beingayogic academy', 'aparnanagar', '9853267321', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('new olympic sports', 'new olympic sports', 'rajabagicha', '8763551569', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('laa femina beaty sallon', 'laa femina beaty sallon', 'bajarakbati rd', '6713590746', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('i physio', 'i physio', 'ranihat', '8763084584', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('pumas cuttack', 'pumas cuttack', 'Cuttack sadar', '7008061866', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('bharat fitness den', 'bharat fitness den', 'jaydev vihar', '8339901557', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kalinga fitness gym', 'kalinga fitness gym', 'sbi bank bbsr', '9439059050', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the dream gym', 'the dream gym', 'sailashree vihar', '8328929165', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('being strong 24', 'being strong 24', 'jharpada', '8984538602', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('knoctout fitness', 'knoctout fitness', 'irc village', '9777145276', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness garage', 'fitness garage', 'abc house', '8093765465', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('life gym', 'life gym', 'lewis rd', '9861426231', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('utkal fitmness club', 'utkal fitmness club', 'acharya viahr', '7381131212', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness mantra gym', 'fitness mantra gym', 'raghunathpur', '9938126363', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fusion fitness', 'fusion fitness', 'chandrashekhar', '9178770114', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('geneva fitness', 'geneva fitness', 'rasugarh', '9861377901', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('galaxy fitzone', 'galaxy fitzone', 'patia', '7735666783', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('qnts fitness', 'qnts fitness', 'patia', '8637270675', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('cult pal height', 'cult pal height', 'jaydev vihar', '9777225580', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('all time fitness 4.0', 'all time fitness 4.0', 'nayapalli', '9776100039', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness hour', 'fitness hour', 'patia', '9853376380', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness mantra gym', 'fitness mantra gym', 'patia', '6372136363', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('beast strength fitness', 'beast strength fitness', 'pandra', '8249799862', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the iron fist gym', 'the iron fist gym', 'jagamara', '9556515701', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('spark fitness', 'spark fitness', 'nayapalli', '8763589199', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('prx fitness', 'prx fitness', 'tamondo', '9937367301', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('midtown burn gym', 'midtown burn gym', 'patia', '7008325736', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('all time fitness 2.0', 'all time fitness 2.0', 'infocity', '9692200891', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('intensityplus fitness center(IFC)', 'intensityplus fitness center(IFC)', 'satya vihar', '9938275276', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ellies fitness hub', 'ellies fitness hub', 'atalagada road', '8260490901', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('maa tara tarininmulti gym', 'maa tara tarininmulti gym', 'rasugarh', '9937542268', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('bhubaneswar health club', 'bhubaneswar health club', 'patia', '7440016701', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('aura athletics', 'aura athletics', 'saheed nagar', '7978896210', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('dynamic gym upgraded', 'dynamic gym upgraded', 'kalinaga nagar', '9090555800', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('dynamic gym', 'dynamic gym', 'jaydev vihar', '9853331455', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('mahima finess gym', 'mahima finess gym', 'padmakeshpur', '7978816645', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('cult gym patia', 'cult gym patia', 'patia', '9861505190', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kinetc strength hub', 'kinetc strength hub', 'rudra pur', '8093300538', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ripped fitness 2', 'ripped fitness 2', 'pandav nagar', '9439716299', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kalinga fitness club', 'kalinga fitness club', 'bharta pur', '9556782331', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ad fitness', 'ad fitness', 'gouri nagar', '7377937079', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('all time fitnes 1.0  jagamara', 'all time fitnes 1.0  jagamara', 'jagmohan nagar', '9937123411', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('AD fitness', 'AD fitness', 'neeladari vihar', '7008100473', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness bull 2.0', 'fitness bull 2.0', 'neeladari vihar', '9937572937', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('power gym', 'power gym', 'saheed nagar', '9778340140', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit life gym', 'fit life gym', 'patia', '9658342921', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('stark the muscle factory', 'stark the muscle factory', 'kalinga nagar', '7008184461', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('energym fitness club', 'energym fitness club', 'acharya viahr', '9583393939', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit life gym', 'fit life gym', 'patia', '9658342921', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('stark the muscle factory', 'stark the muscle factory', 'kalinga nagar', '7008184461', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('curve fitness', 'curve fitness', 'shanti vihar', '7873362836', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit fighter', 'fit fighter', 'gopabandhu square', '7377004444', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('3d fitness', '3d fitness', 'raghunathpur', '7008930562', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('bhbaneswar health', 'bhbaneswar health', 'khandagiri', '7440016705', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('12/7 fitness', '12/7 fitness', 'kharavela nagar', '8338877000', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the iron factory fitness', 'the iron factory fitness', 'patia', '9746236795', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('odisha fitness', 'odisha fitness', 'rasugarh', '8260494440', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('physique gym', 'physique gym', 'baragarh', '7978501815', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('odisha fitness', 'odisha fitness', 'rasugarh', '8260494440', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('maruti nanda fitness club', 'maruti nanda fitness club', 'patia', '6370513423', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('muscle gym', 'muscle gym', 'laxmi sagar', '8249602677', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('muscle gym', 'muscle gym', 'patrapada', '7077772827', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the war house', 'the war house', 'samantara', '9556567133', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('muscle headquter', 'muscle headquter', 'rasugarh', '7992750706', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('a1 fitness', 'a1 fitness', 'patia', NULL, 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('magneto fitness hub', 'magneto fitness hub', 'uttara', '9090000055', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('strennous  fitness', 'strennous  fitness', 'NAYPAILLI', '7381115115', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('holifit lifestyle and fitness center', 'holifit lifestyle and fitness center', 'phulnakhara', '9692308218', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('gr fitness', 'gr fitness', 'siba nagar', '8249445006', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness guru gym', 'fitness guru gym', 'sundarpada', '9178911552', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('team kiran fitness', 'team kiran fitness', 'delta sqaure', '9937667267', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Raw fitness', 'Raw fitness', 'jagamara', '9090850093', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness guru gym', 'fitness guru gym', 'sundarpada', '9178911552', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit fighter', 'fit fighter', 'sahid nagar', '7437004444', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('JH fitness', 'JH fitness', 'kalinga nagar', '7683870747', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fairly ladies gym', 'fairly ladies gym', 'sailashree vihar', '9776201338', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness studio', 'fitness studio', 'near bharatpur', '7008862045', 'gym', true, 'good');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('vigor fitness', 'vigor fitness', 'jagamara', '8594992968', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('sa fitness pro', 'sa fitness pro', 'rasugarh', '9090114545', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the world gym', 'the world gym', 'baramunda', '9861949439', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('icon empire', 'icon empire', 'nayapalli', '7077016179', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('aerofit', 'aerofit', 'sailashree vihar', '9090150510', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('venus gym & fitness world', 'venus gym & fitness world', 'rasugarh', '9437009834', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness world gym', 'fitness world gym', 'sisupalgarh', '9090070556', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ZR Fitness', 'ZR Fitness', 'khandagiri', '9938867567', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('icon empire', 'icon empire', 'nayapalli', '7077016179', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('divine gym', 'divine gym', 'jagamara', '9583784908', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('euro gym', 'euro gym', 'jharpada', '9937137311', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the bhubaneswar', 'the bhubaneswar', 'nayapail', '7077661163', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('b fit gym and zumba center', 'b fit gym and zumba center', 'phulnakhara', '8249783828', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ONE Life wellness', 'ONE Life wellness', 'neeladari vihar', '7978626286', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('body fit', 'body fit', 'irc village', '8270888775', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('jurassic fitness health clkub', 'jurassic fitness health clkub', 'saheed nagar', '7008947742', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('sweet box gym', 'sweet box gym', 'khandagiri', '9658475558', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('HOP : and HB+ stidio', 'HOP : and HB+ stidio', 'chandrashekhar', '9040170666', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('ustayfit gym', 'ustayfit gym', 'saheed nagar', '9338092381', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the fitness den', 'the fitness den', 'irc village', NULL, 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness zone (gym & physiotherapy)', 'fitness zone (gym & physiotherapy)', 'jaydev vihar', '9861231761', 'gym', true, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('All time fitness 1.0', 'All time fitness 1.0', 'jagamara', '9937123411', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kalinga fitness club', 'kalinga fitness club', 'bharatpur', '9556782331', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('dynamic gym', 'dynamic gym', 'jaydev vihar', '9853331455', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('power gym', 'power gym', 'saheed nagar', '9778340140', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('titan forge fitness', 'titan forge fitness', 'laxmi sagar', '7978923901', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('strak the muscle factory', 'strak the muscle factory', 'ghatikia', '7008184461', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('health planet gym', 'health planet gym', 'patia', '9337729258', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('gr fitness', 'gr fitness', 'siba nagar', '8249445006', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kalyan multi gym', 'kalyan multi gym', 'gautam nagar', '9861721180', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fitness arena', 'fitness arena', 'nayapailli', '8637204661', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('oxygen fitness studio', 'oxygen fitness studio', 'puri bypass', '9861296626', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('mg fitness point', 'mg fitness point', 'puri bypass', '7008203439', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('the bhubaneswar', 'the bhubaneswar', 'nayapailli', '7077661163', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('iron empire gym', 'iron empire gym', 'nayapaiili', '7077016179', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('bodyfit', 'bodyfit', 'irc village', '8270888775', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('shape you fitness club', 'shape you fitness club', 'puri canala', '9668600111', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('trikara health club', 'trikara health club', 'puri by pass', '9090229953', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('royale fitness 2.0', 'royale fitness 2.0', 'tulasi vihar', '9090607260', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('mrp fitness', 'mrp fitness', 'patia', '9040170666', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kharvelas fitness', 'kharvelas fitness', 'sisupalgarh', '7008010771', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('city gym', 'city gym', 'sahid nagar', '9853905905', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('stalwart', 'stalwart', 'rasugarh', '8917404305', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('physique gym', 'physique gym', 'baragarh', '7978501815', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit with beat', 'fit with beat', 'sahid nagar', '7849019231', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kings plantinum', 'kings plantinum', 'patia', '9437644368', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('gladiator fitness', 'gladiator fitness', 'satya nagar', '9692987647', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('shefit studio', 'shefit studio', 'nayapailli', '9437512667', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fairly ladies gym', 'fairly ladies gym', 'sailashree vihar', '9776201338', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('royal fitness gyma', 'royal fitness gyma', 'patia', '9583275250', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('good life gym and fitness', 'good life gym and fitness', 'sailashree vihar', '9556670890', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('iron hour gym', 'iron hour gym', 'jagamohan nagar', '7205638826', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('r.v gym', 'r.v gym', 'pandav nagar', '9937842666', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit with beat', 'fit with beat', 'saheed nagar', '7849019231', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('king plantinum gym', 'king plantinum gym', 'patia', '9437644368', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('mahaveer fitness', 'mahaveer fitness', 'baramunda', '8908161115', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('kato''s gym', 'kato''s gym', 'niladri bihar', '9658406900', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('fit queen gym', 'fit queen gym', 'irc village', '9437119208', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('adyashakti fitness gym', 'adyashakti fitness gym', 'bhimatangi', '9583311119', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('biju patnaik swaimming complex gym', 'biju patnaik swaimming complex gym', 'nayapailli', '7008351416', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('classic fitness', 'classic fitness', 'khandagiri', '9937004727', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('shreejagnath health club', 'shreejagnath health club', 'sameigadia', '9778039927', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('aura gym kiit area behind kp - v', 'aura gym kiit area behind kp - v', 'sikharchandi vihar', '7873953337', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('smile yoga', 'smile yoga', 'SARALA NAGAR', '9556188012', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('unicorn gym', 'unicorn gym', 'saheed nagar', '9861263671', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Gopabandhu Fitness Center', 'Gopabandhu Fitness Center', 'gopabandhu nagar', '9658184749', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('RK Gym & Fitness', 'RK Gym & Fitness', 'Pandab Nagar, BBSR', '7606992872', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Harmony Fitness', 'Harmony Fitness', 'Mancheswar', '9438249520', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('The kettle bell', 'The kettle bell', 'Rasulgad, BBSr', '7377788651', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Mas fintess Factory', 'Mas fintess Factory', 'Jharpada', '9438124046', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Fitness Park', 'Fitness Park', 'Barmunda', '6742354818', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('DK 2 More Fitness', 'DK 2 More Fitness', 'Khandagiri', '7008060780', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Mahavir Gym', 'Mahavir Gym', 'Nayapallli', '8252354763', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Crossfit Gym', 'Crossfit Gym', 'Nayapalli', '7008938428', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Solid Health Gym', 'Solid Health Gym', 'Forest Park, BBSR', '7978454995', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Mudra Fitness', 'Mudra Fitness', 'Jharpada', '7259031876', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Pro-Fit Unisex Gym', 'Pro-Fit Unisex Gym', 'Gadachandi Market Complex', '8093289717', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Muscle Take Multi Gym', 'Muscle Take Multi Gym', 'Rashulgada, BBsr', '7504053873', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Jaguars Fitness Lounge', 'Jaguars Fitness Lounge', 'Ashok Nagar', '6742531890', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Stalwart xanadu', 'Stalwart xanadu', 'chandra sekhar pur', '7077671215', 'gym', true, 'average');
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Bhubaneswar Health Club', 'Bhubaneswar Health Club', 'Nayapalli', '7440016703', 'gym', false, NULL);
INSERT INTO public.leads (name, company, address, phone, category, has_website, website_quality) VALUES ('Mahavir Multi Gym', 'Mahavir Multi Gym', 'Rasulgada', '7978165945', 'gym', false, NULL);